---
- name: Let's copy our executable script to remote location, execute script and get result back.
  remote_user: ansible-user
  become: yes
  any_errors_fatal: false
  hosts: auditlog-group
  vars:
      date: "{{ lookup('pipe', 'date +%Y%m%d-%H%M') }}"

  tasks:
       - name: Transfer the command logrotate cron to /etc/logrotate.d
         copy: src=/root/samie/commands dest=/etc/logrotate.d/commands mode=0644
 
       - name: Zip the command log if more than 500MB
         archive:
              path: /var/log/commands.log
              dest: /var/log/commands.log_{{date}}.zip
              format: zip
              remove: yes
         ignore_errors: yes

       - name: make sure commands.log is present
         file:
              path: "/var/log/commands.log"
              state: touch
